# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PinVid' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PinVid
	pod 'Firebase/Core'
  target 'PinVidTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PinVidUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
